#fish.template = 'fishcolors.theme'
# Catppuccin
# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
# 
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "catppuccin-mocha"

# ========= Border =========
file_panel_border = "{{color2 | blend(color12) | darken(0.4)}}"
sidebar_border = "{{color2 | blend(color12) | darken(0.4)}}"
footer_border ="{{color2 | blend(color12) | darken(0.4)}}"

# ========= Border Active =========
file_panel_border_active = "{{color2}}"
sidebar_border_active ="{{color2}}"
footer_border_active = "{{color2}}"
modal_border_active = "{{color2}}"

# ========= Background (bg) =========
full_screen_bg = "{{background}}"
file_panel_bg = "{{background}}"
sidebar_bg = "{{background}}"
footer_bg = "{{background}}"
modal_bg = "{{background}}"

# ========= Foreground (fg) =========
full_screen_fg = "{{color2 | blend(foreground) | darken(0.2)}}"
file_panel_fg ="{{color2 | blend(foreground) | darken(0.2)}}"
sidebar_fg = "{{color2 | blend(foreground) | darken(0.2)}}"
footer_fg ="{{color2 | blend(foreground) | darken(0.2)}}"
modal_fg = "{{color2 | blend(foreground) | darken(0.2)}}"

# ========= Special Color =========
cursor = "#f5e0dc"
correct = "#a6e3a1"
error = "#f38ba8"
hint = "#73c7ec"
cancel = "#eba0ac"
# Gradient color can only have two color!
gradient_color = ["#89b4fa", "#cba6f7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "{{color4}}"
file_panel_top_path = "{{color2 | blend(color4)}}"
file_panel_item_selected_fg = "#98D0FD"
file_panel_item_selected_bg = "{{background}}"

# ========= Sidebar Special Items =========
sidebar_title = "{{color2 | blend(color4)}}"
sidebar_item_selected_fg = "#A6DBF7"
sidebar_item_selected_bg = "{{background}}"
sidebar_divider = "#868686"

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = "#eba0ac"

modal_confirm_fg = "#383838"
modal_confirm_bg = "#89dceb"

# ========= Help Menu =========
help_menu_hotkey = "{{color2}}"
help_menu_title = "{{color3}}"
